NET-340
gravitl/netmaker-docs pull request #170
Opened 2023-07-26 21:45 UTC by uGiFarukh

* Added documentation for multi-server support on netclient.

2023-07-26 21:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/gravitl/netmaker-docs?pullRequest=170) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/gravitl/netmaker-docs?pullRequest=170) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/gravitl/netmaker-docs?pullRequest=170) it.</sub>

2023-07-27 00:23 UTC, theguy951357 approved these changes

2023-07-27 10:00 UTC, abhishek9686 requested changes

2023-07-27 10:03 UTC, uGiFarukh commented on netclient.rst
> +Netclient can be used with multiple netmaker servers. You can switch between different netmaker servers using netclient switch command. Swithing to another server will disconnect netclient from all t
got it

2023-07-27 12:09 UTC, mattkasun approved these changes

2023-07-27 12:11 UTC, merged