feat(NET-478): add client metrics
gravitl/netmaker-docs pull request #179
Opened 2023-08-03 11:26 UTC by Aceix

![image](https://github.com/gravitl/netmaker-docs/assets/8738443/19c08821-2ec8-42a6-a9be-6a777aeb956a)

2023-08-03 11:54 UTC, mattkasun requested changes

2023-08-03 11:54 UTC, mattkasun commented on ee/ee-metrics.rst
> +From here, you can switch to any metric you are interested in, includeng metrics from clients.
Typo : including

2023-08-10 17:42 UTC, abhishek9686 approved these changes

2023-08-10 18:55 UTC, mattkasun approved these changes

2023-08-11 11:35 UTC, merged