docs(NET-497): add join with endpoint and port
gravitl/netmaker-docs pull request #180
Opened 2023-08-08 19:48 UTC by Aceix

2023-08-08 20:08 UTC, mattkasun requested changes

2023-08-08 20:08 UTC, mattkasun commented on netclient.rst
> +  netclient join -n <net name> -t <token> -e <ip address> -p <listen port>
-n with -t does not make sense as the token includes the networks to join

2023-08-11 10:05 UTC, mattkasun approved these changes

2023-12-12 09:53 UTC, Aceix commented
closing stale PR. netclient current implementation does not tally with this

2023-12-12 09:53 UTC, closed without merging