instructions for upgrades to v0.20.6
gravitl/netmaker-docs pull request #182
Opened 2023-08-09 15:35 UTC by mattkasun

2023-08-09 15:40 UTC, theguy951357 requested changes

2023-08-09 15:40 UTC, theguy951357 commented on upgrades.rst
> +As of 0.13.0, and up 0.17.1 upgrading Netmaker is a manual process. As of 0.20.6 the upgrade process from 0.17.1 to current vesrsion has been automated.
typo vesrsion -> version

2023-08-09 15:40 UTC, theguy951357 commented on upgrades.rst
> +3. If upgrading from EE to EE, a new licence key and tennet id must be obtained from https://app.netmaker.io
tennet -> tenant

2023-08-10 17:10 UTC, theguy951357 approved these changes

2023-08-10 17:31 UTC, abhishek9686 requested changes

2023-08-10 17:31 UTC, abhishek9686 commented on upgrades.rst
> +1. Download the nm-upgrade.sh script from https://fileserver.netmaker.io/upgrades/nm-upgrade.sh; make the script executable and run it
can you mention to run the script on the server

2023-08-11 16:24 UTC, Aceix approved these changes

2023-08-14 11:58 UTC, abhishek9686 requested changes

2023-08-14 11:58 UTC, abhishek9686 commented on upgrades.rst
we should also mention about extclients need to be re-created

2023-08-14 14:13 UTC, theguy951357 approved these changes

2023-08-14 16:18 UTC, abhishek9686 requested changes

2023-08-14 16:18 UTC, abhishek9686 commented on upgrades.rst
> +1. Download the nm-upgrade.sh script from https://fileserver.netmaker.io/upgrades/nm-upgrade.sh; make the script executable and run it
fix link `https://fileserver.netmaker.io/upgrade/nm-upgrade.sh`

2023-08-14 17:43 UTC, abhishek9686 approved these changes

2023-08-14 17:43 UTC, merged