update ee user management docs
gravitl/netmaker-docs pull request #204
Opened 2023-09-01 15:23 UTC by pwilson77

2023-09-01 15:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/gravitl/netmaker-docs?pullRequest=204) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/gravitl/netmaker-docs?pullRequest=204) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/gravitl/netmaker-docs?pullRequest=204) it.</sub>

2023-09-01 15:28 UTC, Aceix requested changes

2023-09-01 15:28 UTC, Aceix commented on pro/pro-users.rst
> +* Admin: An admin has full access to the Netmaker dashboard. They can create and manage users, networks, and gateways. They can also manage user permissions.
missing notes on superuser

2023-09-01 15:28 UTC, Aceix commented on pro/pro-users.rst
> +Attaching or removing user from ingress
let's say "Client Gateway" instead of "Ingress'

2023-09-01 15:28 UTC, Aceix commented on pro/pro-users.rst
> +To attach users to a gateway ore remove users from a gateway, you will need to have the gateway set up.
typo "or" not "ore"

2023-09-01 15:28 UTC, Aceix commented on pro/images/dashboard-no-access.png
this page is not in the new ui. we shouldnt add it

2023-09-04 04:38 UTC, abhishek9686 requested changes

2023-09-04 04:38 UTC, abhishek9686 commented on pro/pro-users.rst
@pwilson77  also mention that only superadmin and admins can visit the dashboard
Touch Upon the normal users with gateways and users functionality with remote access client

2023-09-07 05:43 UTC, abhishek9686 commented on pro/pro-users.rst
> +To attach users to a gateway or remove users from a gateway, you will need to have the gateway set up.
gateway -> client gateway

2023-09-07 05:56 UTC, abhishek9686 requested changes

2023-09-07 05:56 UTC, abhishek9686 commented on pro/pro-users.rst
> +Once the gateway is set up, you will see an option to remove users from the dropdown menu.
gateway -> client gateway

2023-09-11 17:24 UTC, abhishek9686 requested changes

2023-09-11 17:24 UTC, abhishek9686 commented on pro/pro-users.rst
> +In the dropdown menu, an option to transfer admin rights should be present. On clicking it, a dialog box will open allowing you to select any admin
`In the dropdown menu, an option to transfer admin rights should be present` -> you will see an option to transfer admin rights`

2023-09-11 17:24 UTC, abhishek9686 commented on pro/pro-users.rst
> +Then they will have to select a network and subsequently a client gateway to use and after click on connect
`Then they will have to select a network and subsequently a client gateway to use and after click on connect`. -> `After successful login you will be shown all the networks and gateways you have given access to, so now you will be able to connect/disconnect/refresh your connection to a gateway`

2023-09-11 17:53 UTC, pwilson77 commented on pro/pro-users.rst
> +Once the gateway is set up, you will see an option to remove users from the dropdown menu.
done

2023-09-11 18:29 UTC, Aceix approved these changes

2023-09-11 18:30 UTC, abhishek9686 approved these changes

2023-09-11 18:30 UTC, merged