NET-383
gravitl/netmaker-docs pull request #210
Opened 2023-09-14 10:28 UTC by uGiFarukh

* Documentation for new netclient push command and netclient join command.
* Some cleanup for previous netclient configurations.

NET-502 was responsible for updating the docs for NET-383

2023-10-10 06:26 UTC, abhishek9686 requested changes

2023-10-10 06:26 UTC, abhishek9686 commented on examplecode/netclient-help.txt
> +   version     Displays version information
push cmd?

2023-10-11 20:20 UTC, uGiFarukh commented on examplecode/netclient-help.txt
> +   version     Displays version information
Added with new commit.

2023-10-12 06:36 UTC, abhishek9686 approved these changes

2023-10-12 06:36 UTC, abhishek9686 commented
@uGiFarukh resolve merge conflicts

2023-10-17 07:32 UTC, merged