docs(NET-1125): add download links for RAC mobile
gravitl/netmaker-docs pull request #295
Opened 2024-04-10 12:47 UTC by Aceix

2024-04-11 12:17 UTC, abhishek9686 requested changes

2024-04-11 12:17 UTC, abhishek9686 commented on pro/rac.rst
can we display qr code instead of links?
that will be easier for user to just use their mobile phone to scan and visit the app

2024-04-12 11:59 UTC, Aceix commented on pro/rac.rst
![image](https://github.com/gravitl/netmaker-docs/assets/8738443/4d98d8dd-890c-4ca5-871c-57946f458803)

2024-04-17 19:30 UTC, theguy951357 commented on pro/rac.rst
> +**For Windows**, you can download the remote-access-client_86.msi installer and run it to install on your windows machine. The app will need to be run as administrator. Right click on the desktop ico
include both msi and bundle exe file link. admin instructions not needed.

2024-04-17 19:30 UTC, theguy951357 commented on pro/rac.rst
> +**For Mac**, You can download the mac installer from the fileserver link above and run it. Because the app needs to be run as root, open a teminal and enter the command ``sudo /Applications/NetmakerR
no longer need to run as sudo. installer is fixed.

2024-04-18 18:05 UTC, abhishek9686 approved these changes

2024-04-18 18:05 UTC, merged