Update Pro setup docs
gravitl/netmaker-docs pull request #304
Opened 2024-05-17 13:42 UTC by NEETweeb

https://toil.kitemaker.co/cQARgD-Gravitl/6a50SD-Netmaker/items/1211

2024-05-17 17:50 UTC, Aceix reviewed
The billing process just changed so it might affect this pr

2024-07-17 10:58 UTC, abhishek9686 commented
pricing page needs to be updated @NEETweeb

2024-07-22 03:54 UTC, abhishek9686 requested changes

2024-07-22 03:54 UTC, abhishek9686 commented on netclient.rst
> +Firewall Settings
Firewall Settings should be moved to the prereqs section (this is added in the develop branch, pull the latest changes to your branch). we should include firewall settings required for the netmaker server as well
we have an old section for the server already, refer here - https://docs.netmaker.io/manual-install.html#open-firewall

2024-07-22 17:53 UTC, abhishek9686 approved these changes

2024-07-22 17:54 UTC, merged